version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes: # This volume helps us to update our docker image with  any chnages that we can make in our project in realtime
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
